### ISSUE TITLE
07.13开始，运行报错  TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by nanvon** [bambooom/douban-backup#99]
```
Run node sync-rss.js || exit 1
Refreshing feeds from RSS...
file:///home/runner/work/douban-backup/douban-backup/sync-rss.js:297
  const m = title.match(allStatus)[1];
                                  ^

TypeError: Cannot read properties of null (reading '1')
    at extractItemInfo (file:///home/runner/work/douban-backup/douban-backup/sync-rss.js:297:35)
    at file:///home/runner/work/douban-backup/douban-backup/sync-rss.js:79:38
    at Array.forEach (<anonymous>)
    at main (file:///home/runner/work/douban-backup/douban-backup/sync-rss.js:78:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Process completed with exit code 1.
```

**Comment by bambooom** [comment]
能不能具体贴给我你这个失败的 action的link，还有你的豆瓣的 link

**Comment by nanvon** [comment]
> 能不能具体贴给我你这个失败的 action的link，还有你的豆瓣的 link

Action Link: https://github.com/nanvon/douban-backup/actions/runs/5570917301
Douban: https://www.douban.com/people/nanvon/

**Comment by bambooom** [comment]
@nanvon  已经修好了

**Comment by nanvon** [comment]
@bambooom 3Q
